### ISSUE TITLE
about the input data

### ISSUE THREAD

**Issue by yangfen669** [thunlp/Fast-TransX#10]
in the train.txt,   the formal  (e1, e2, rel)  represent the triples, example
/m/027rn	    /m/06cx9   	/location/country/form_of_government,  I want to know  what's mean of  the /m/027rn or  /m/06cx9. how to understand the entity? 

thank you very much.

**Comment by THUCSTHanxu13** [comment]
Both "/m/027rn" and "/m/06cx9" are entity ids in Freebase. If you want to understand the entity, you must find the details in Freebase (https://developers.google.com/freebase/) with its id.

**Comment by zhangyi85** [comment]
1  运行了您fastTransE的代码，在训练过程中，好像迭代30次左右，res就达到0了，那后面的迭代还有意义么？
2  您的代码中，没有考虑随机选取方式bern，以及L2范式度量距离，是么？

**Comment by zhangyi85** [comment]
运行fastTransH，一轮后res就降为0。太快了吧

**Comment by zhangyi85** [comment]
补充一下，用的是freebase15的数据集

**Comment by THUCSTHanxu13** [comment]
能具体说一下freebase15数据集的具体情况吗

**Comment by zhangyi85** [comment]
用的是您从fb15k转换过的entity2id.txt，relation2id.txt ，triple2id.txt

**Comment by zhangyi85** [comment]
fastTrainH迭代第一次是6338.687012，后面的都是0.000000

**Comment by zhangyi85** [comment]
请问您常用的邮箱地址？@THUCSTHanxu13

**Comment by THUCSTHanxu13** [comment]
cst_hanxu13@163.com
