### ISSUE TITLE
how to test the training result?

### ISSUE THREAD

**Issue by FengliLin** [thunlp/Fast-TransX#12]
hello, I'd like to know how to test the training result?
Thanks!

**Comment by zhangyi85** [comment]
用test程序去跑训练模型

**Comment by fedorn** [comment]
I am using test programs from https://github.com/thunlp/KB2E. You just have to remove fist lines from *2id.txt files. Unfortunately, it is not as fast as code in this repo. Could authors also provide efficient implementation of test programs?

**Comment by zhangyi85** [comment]
would you provide the detail hyper-parameter in the optimal configration in the readme？
