### ISSUE TITLE
请问尝试过在构造负例时使用替换关系的方式替换头尾实体么？

### ISSUE THREAD

**Issue by zhangyi85** [thunlp/Fast-TransX#13]
我尝试用替换关系的方式构造负例，效果不是太好，不知道是否是编码的问题。请教各位大牛，是否做过这方面的尝试，谢谢～

**Comment by THUCSTHanxu13** [comment]
实体数量远远多于关系，负例全集是包含替换实体以及替换关系的，替换关系的覆盖面没有替换实体来的大

**Comment by ProKil** [comment]
一般只替换实体的话，效果就已经不错了。再加上替换关系，还可以再提升一些。但是只替换关系的话效果就会比较差。

**Comment by zhangyi85** [comment]
您说的再加上替换关系是什么意思？给一部分替换概率给关系？

**Comment by ProKil** [comment]
嗯 可以这样实现

**Comment by zhangyi85** [comment]
请问如何设置关系的替换概率比较合理？

**Comment by THUCSTHanxu13** [comment]
可以50%替换实体，50%替换关系

**Comment by zhangyi85** [comment]
替换实体部分，在按照之前头尾实体的替换概率来替换头尾实体？

**Comment by THUCSTHanxu13** [comment]
Knowledge graph embedding by translating on hyperplanes讲了实体替换规则，你可以看一下

**Comment by zhangyi85** [comment]
明白，实体部分按照transH方式替换

**Comment by zhangyi85** [comment]
多谢～
