### ISSUE TITLE
有没有人在windows下用vc++编译过？

### ISSUE THREAD

**Issue by zhangyi85** [thunlp/Fast-TransX#14]
有没有人在windows下用vc++编译过？跑的结果如何？

**Comment by THUCSTHanxu13** [comment]
没有试过，在windows下也可以装mingw用g++

**Comment by zhangyi85** [comment]
在网上找了一个pthreads在Windows下的移植库，可以将代码编译运行起来，但是出现了在训练过程中，第一次迭代res有值，后面的全为0，同样代码在solaris下，值不一样😓

**Comment by THUCSTHanxu13** [comment]
没有考虑跨平台，你装个ubuntu跑吧。。。
