### ISSUE TITLE
transR 段错误 (核心已转储)

### ISSUE THREAD

**Issue by wangdsh** [thunlp/Fast-TransX#15]
$ ls
data  out  transR.cpp
$ ls data/
entity2id.txt  relation2id.txt  triple2id.txt
$ g++ transR.cpp -o transR -pthread -O3 -march=native
$ ./transR
段错误 (核心已转储)

我在尝试运行transR的时候遇到这个问题，请问这是我执行过程有问题，还是代码哪里有问题？
运行环境：Ubuntu 16.04.02

**Comment by THUCSTHanxu13** [comment]
FILE* f1 = fopen((inPath + "transRdata/entity2vec.bern").c_str(),"r");
	for (int i = 0; i < entityTotal; i++) {
		for (int ii = 0; ii < dimension; ii++)
			tmp = fscanf(f1, "%f", &entityVec[i * dimension + ii]);
		norm(entityVec + i * dimension, dimension);
	}
	fclose(f1);
	FILE* f2 = fopen((inPath + "transRdata/relation2vec.bern").c_str(),"r");
	for (int i=0; i < relationTotal; i++) {
		for (int ii=0; ii < dimension; ii++)
			tmp = fscanf(f2, "%f", &relationVec[i * dimensionR + ii]);
	}
	fclose(f2);
       需要transE的结果作为初始化参数输入，你少了这两个文件
