### ISSUE TITLE
您好，不太理解您测试程序中test函数开始要做6次循环

### ISSUE THREAD

**Issue by zhangyi85** [thunlp/Fast-TransX#18]
您好，不太理解您测试程序中test函数开始要做6次循环。跑出来结果有6组，之前还以为后面4组是1对1，1对多，多对1和多对多的结果。

**Comment by zhangyi85** [comment]
能否把每个模型最优结果的详细参数配置提供，非常感谢！

**Comment by THUCSTHanxu13** [comment]
因为还有一种测试是加了关系限制的实体预测(Type-Constrained Representation Learning in Knowledge Graphs)，主要这段时间事情比较多就先扔上来一个能用的版本，过一段时间应该会加一段说明 = =！

模型的最优结果的话你用我的默认参数然后调整下维度效果也还不错，具体参数你可以看一下附录里的那些模型论文。

**Comment by zhangyi85** [comment]
那请问测试结果怎么看呢？前面两个是总结果，后面四个对应1-1,1-m,m-1,m-m？
@THUCSTHanxu13

**Comment by zhangyi85** [comment]
不知道理解错了没，第0行是原始transE，第1行是加了类型限制的结果？

**Comment by THUCSTHanxu13** [comment]
是的

**Comment by zhangyi85** [comment]
非常感谢！ @THUCSTHanxu13
