### ISSUE TITLE
请问一下，entityVecDao是什么变量，有点困惑

### ISSUE THREAD

**Issue by HongxuChenUQ** [thunlp/Fast-TransX#19]

**Comment by THUCSTHanxu13** [comment]
主要用在训练的时候entityVec来计算梯度，然后梯度变好后的结果放在entityVecDao里，一轮结束后再把entityVecDao再存回entityVec里，这就是一个用来进行batch求梯度的数据备份，当时随便取的名字(Dao, data alternating object)
