### ISSUE TITLE
请问type_constrain.txt的生成方式及作用

### ISSUE THREAD

**Issue by AltenLi** [thunlp/Fast-TransX#20]
读代码的时候，看测试中有type_constrain.txt，这个是怎么产生的呢?
是基于训练集跑出的与p关联的s list和o list么？
以及作用是什么，谢谢~

**Comment by THUCSTHanxu13** [comment]
这个主要是用来测试的。在一般测试的时候对于给定实体(h,r,t)，我要将t换成其他实体来判断(h,r,t)的得分函数排在多少。不过有种测试方式会加一些限制，比如t的替换项不是全部实体集合中的元素，而是关系r右侧可能出现的实体集合元素，type_constrain.txt就是统计每个关系左侧右侧可能出现的实体集合。这种测试方式比较奇怪，绝大多数时候并没有被使用，一般只是用在大规模的数据上。

**Comment by angryBird2014** [comment]
可以把type_constrain.txt的代码发布出来吗？
