### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by daniilsorokin** [thunlp/Fast-TransX#21]
Hello,

I have just managed to run it locally and I wanted to point out that some of the documentation is a bit misleading. 

The description of the input file format should mention that triple2id.txt contains ids from entitiy2id and relation2id and not the names of the entities and relations. It is different from https://github.com/thunlp/KB2E. At first, I though that I can use just the same input files. 

It is unclear what does the -nbatches parameter does. The default setting (=1) works best for me, but i don't get why.

Otherwise, thank you for the great package!

Daniil

**Comment by ProKil** [comment]
1. We apologize for the inconvenience. Thanks for pointing out!
2. We have tried mini-batch training as well. However, as you have pointed out, batch size = 1 is the optimal setting in most cases.

Best,
Hao

**Comment by ProKil** [comment]
Commit 94f22da7f77247a445854bee1659d31e86c062f5 fixed 1.

**Comment by daniilsorokin** [comment]
Great! Thanks for a quick fix! I guess we can close it.
