### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by syllenz** [thunlp/Fast-TransX#22]
你好，我照此执行：
cd transE
g++ transE.cpp -o transE -pthread -O3 -march=native
编译出错，提示：
transE.cpp:1: error: bad value (native) for -march= switch
transE.cpp:1: error: bad value (native) for -mtune= switch
请帮忙看看

**Comment by THUCSTHanxu13** [comment]
你把-march=native去掉试试看，可能你机器的指令集比较奇怪。
