### ISSUE TITLE
Fast_transE在WN18数据集的结果与给出相差较大

### ISSUE THREAD

**Issue by RichardHGL** [thunlp/Fast-TransX#25]
您好！我用当前版本的fast-transe和前一两个版本跑WN18数据集
出来的结果大致如下（参数使用size = 50，epoch = 1000，alpha = 0.001）
left 426.596802 0.798800
left(filter) 411.633392 0.943800
right 446.216400 0.808000
right(filter) 432.734406 0.941200
网站给出结果如下：
mean_rank|mean_rank_filter|hits@10|hits@10_filter
273 | 261 | 71.5 | 83.3
相差较大，请问是哪里有问题吗？还是数据和最初的WN18有变化了

**Comment by THUCSTHanxu13** [comment]
当时是我随便一个默认参数跑的，我没有仔细调参，理论上wn18结果差不多是90多，我给的数据就是最初的WN18，没有变化。不过我实现的transE和以往的还是有点区别的，底层采样不太一样，然后也没有了batch，但这个理论上影响不是特别大。

**Comment by HongxuChenUQ** [comment]
想问一下，我看transR论文中给出的是算h+r-t的L2norm 为什么代码理采用的好像是L1？

**Comment by RichardHGL** [comment]
好的，谢了!

**Comment by HZhang90** [comment]
您好，我用的参数

INT threads = 8;
INT bernFlag = 0;
INT loadBinaryFlag = 0;
INT outBinaryFlag = 0;
INT trainTimes = 1000;
INT nbatches = 1;
INT dimension = 50;
REAL alpha = 0.001;
REAL margin = 1.0;

在wn18上跑TransE，结果却非常差，请问可能是哪里错了呢：

left 1226.356201 0.221600
left(filter) 1216.166016 0.232600
right 1402.401367 0.204600
right(filter) 1392.722656 0.235600
left 369.013214 0.400800
left(filter) 358.822998 0.419600
right 281.390411 0.339200
right(filter) 271.711609 0.377600
left 1095.500000 0.523810
left(filter) 1095.309570 0.523810
right 825.595215 0.547619
right(filter) 825.428589 0.547619
left 1188.984863 0.190579
left(filter) 1188.887939 0.191121
right 1205.759033 0.145642
right(filter) 1180.281006 0.209529
left 1651.449219 0.066633
left(filter) 1626.444214 0.078243
right 2118.939941 0.060071
right(filter) 2118.886475 0.060071
left 547.074341 0.532743
left(filter) 545.986755 0.560177
right 489.092926 0.541593
right(filter) 488.010620 0.574336

谢谢指教！
