### ISSUE TITLE
TransR实验结果问题

### ISSUE THREAD

**Issue by angryBird2014** [thunlp/Fast-TransX#29]
我用Fast-transR跑WN11的时候，没有用其他的程序训练的embedding，按照alpha = 0.001,batch_size = 100,dimension = 50,margin = 1时训练，测试时的效果非常差，meanRank平均都有几千了，Hit@10只有0.00几，这显然不对，能否告诉readme的实验结果是如何跑出来的?

**Comment by THUCSTHanxu13** [comment]
首先你需要预训练transE，然后将transE的向量作为transR的初始化接着训练。另外，数据集合需要重新调整参数，alpha 0.001， margin 1是给fb的数据集准备的。WN的数据集一般维度不能特别高，学习率也要大一点，margin好像也有设大，这个我有点忘记了。反正训练很快，你试一下 = =！

**Comment by angryBird2014** [comment]
好的，我重新pre-train试一下
