### ISSUE TITLE
What's in file 'transRdata/entity2vec'?

### ISSUE THREAD

**Issue by hfsugar** [thunlp/Fast-TransX#3]
When I saw this : FILE* f1 = fopen((inPath + "transRdata/entity2vec.bern").c_str(),"r");
                            FILE* f2 = fopen((inPath + "transRdata/relation2vec.bern").c_str(),"r");
I wanna know what are these two files?
Thank you very much!

**Comment by THUCSTHanxu13** [comment]
These files are the results of the TransE. TransR will get better results based on the TransE results.
