### ISSUE TITLE
TransR 的Mean Rank 和 Hits@10的问题？

### ISSUE THREAD

**Issue by tnbaby** [thunlp/Fast-TransX#30]
测试TransR 的时候Mean Rank 是right 和left 取均值还是选最好的？

**Comment by angryBird2014** [comment]
取均值吧

**Comment by tnbaby** [comment]
如果取均值的话， 我一直调不出transR 论文里的mean rank，始终是200多，你的超参方便告诉一下吗？

**Comment by THUCSTHanxu13** [comment]
你是不是bernflag设成了1？

**Comment by tnbaby** [comment]
不是啊，一直用的unif 模式 bernflag = 0

**Comment by THUCSTHanxu13** [comment]
你测试的哪个数据啊

**Comment by angryBird2014** [comment]
@tnbaby 加个qq交流一下?1196697665
