### ISSUE TITLE
关于test2id_all.txt中第一列label的作用

### ISSUE THREAD

**Issue by yuanyuansiyuan** [thunlp/Fast-TransX#31]
请问在test2id_all.txt中第一列的label是如何生成的呢？如果用自己的数据集来跑实验，需要如何构造？
谢谢！

**Comment by THUCSTHanxu13** [comment]
这个label主要是判断这个每一行三元组的关系是1-1，1-n，n-1，n-n里面的哪一个，每个数据集合里面有一个n-n.py	用来生成这个东西，你可以看一下
