### ISSUE TITLE
关于TransE实验结果的问题

### ISSUE THREAD

**Issue by yuanyuansiyuan** [thunlp/Fast-TransX#32]
在使用自己的数据集跑TransE的时候出现了维度较低时 meanRank很高，但hits@10指标却很好的情况（0.8)，但拿这个embedding去做其他任务比如推荐效果很差，这大概是什么原因呢？为什么两个指标有这种不一致的情况？我的数据集情况： epoch =1000 dimension=20 lrate =0.1  数据集 6w实体，40w元组，6种关系，每个节点大概有6条边， 是一个音乐实体的数据集。

**Comment by THUCSTHanxu13** [comment]
话说，你学习率这么高不会过拟合嘛。。。meanrank受长尾影响比较大，有几个长尾的实体训练不到，涉及他们的三元组的rank就可能非常的高。训完之后建议你输出一些实体看一下他们最相近的实体是哪些，人眼看一下是不是靠谱。推荐比较差的具体原因可能还需要你这边自己分析了

**Comment by yuanyuansiyuan** [comment]
谢谢您的及时回复。好的，我会在预测时观察下预测结果是否合理。 在SGD中学习率过高不是会可能越过最优解，在测试集上效果变差么，请问为什么会过拟合呢？另外我的n-1,n-n的评测结果是meanrank为0， hits@10为1.0， 分别有700和1w的元组。 另外请问TransR的调参dimension, margin,lrate哪些比较敏感，我这边一直跑不出比较好的结果，麻烦了，非常感谢！

**Comment by THUCSTHanxu13** [comment]
TransR要在TransE预训练好的向量上再跑，直接随机初始化开始很难收敛到一个比较好的结果。
