### ISSUE TITLE
请问transE中nbatches = 1，这个参数是什么意义？大小应该随着训练集的大小怎么改变吗？蟹蟹！

### ISSUE THREAD

**Issue by daoqingcheng** [thunlp/Fast-TransX#33]

**Comment by THUCSTHanxu13** [comment]
在其他的几个模型里面，nbatches是所有的数据在一轮之中分几个batch训练完。transE里面我在梯度传播的时候每一个直接回传了梯度，所以transE里面这个你可以不用调，对结果影响不大。。。。

**Comment by daoqingcheng** [comment]
好的！蟹蟹。我跑了附带的FB15K的数据，1000个epoch后res还是1000+，是可以接受的结果吗？还是说我应该再自检？

**Comment by THUCSTHanxu13** [comment]
训练的时候输出的值是loss，FB15K的话1000多轮1000+应该差不多，具体结果你测试下就行了，我这个测试程序也很快的，要不了几分钟

**Comment by daoqingcheng** [comment]
非常感谢~你们的工作真的很棒！

**Comment by haidfs** [comment]
> 训练的时候输出的值是loss，FB15K的话1000多轮1000+应该差不多，具体结果你测试下就行了，我这个测试程序也很快的，要不了几分钟

transe的损失值大概收敛在一个什么值？
