### ISSUE TITLE
预测头实体的效果（left）比预测尾实体(right）效果好的原因？

### ISSUE THREAD

**Issue by ECNU109** [thunlp/Fast-TransX#34]
自己的数据集和示例数据集跑出来都是预测头实体的效果（left）比预测尾实体(right）效果好，请问这是什么原因？

**Comment by THUCSTHanxu13** [comment]
这个和你数据的关系类型有关吧，比如性别，（小明，性别，男）预测（小明，性别，？）远比（？，性别，男）要简单的多

**Comment by yuanyuansiyuan** [comment]
我现在是通过链接预测来做推荐，针对听歌关系，用户有100个，歌曲有3w, 从数量上来说，预测<用户--？>来给用户推荐歌曲 比 <歌曲被哪些用户听> 要难，是这样理解么？ 另外我用的是用户的听歌记录和音乐知识图谱混合的图谱来embedding，只想看听歌关系的预测效果，是不是需要看第二个type-constrain的效果？ 限制候选集只是歌曲或用户
谢谢！

**Comment by yuanyuansiyuan** [comment]
我拿听歌记录和音乐知识图谱来embedding ， 只对听歌关系进行预测

**Comment by ProKil** [comment]
不太清楚你的具体情境。不过做一个clarification， 这个更难的说法其实并不是那么准确，其实只是在统计指标上会比较落后。比如，对于三个正确答案，即使他们的排名是前三个，mean rank=3/2；而一个正确答案，排名第一的话，mean rank=1。这其实是统计指标上的问题。
