### ISSUE TITLE
Segmentation fault with TransR while running the test_transR

### ISSUE THREAD

**Issue by niladri-paul** [thunlp/Fast-TransX#35]
Hi,

I am using the transR and WN18 data to train. Training is fineing. Then I am using the output .vec and the given test2id.txt given in the WN18 directory to make an inference from the data using test_transR. Now I am getting a segmentation fault(core dumped). Can someone tell me how to fix this issue?

**Comment by ProKil** [comment]
Sorry for our late response.

Segmentation faults most probably occur when input files are not at their right location. Could you please first check this issue?

Thanks,
-Hao

**Comment by niladri-paul** [comment]
Dear Hao,

Thanks a lot. I had figured it out. Now the training is working perfectly.

Thanks,
Niladri
