### ISSUE TITLE
transR无法重现页面上的结果

### ISSUE THREAD

**Issue by chivychao** [thunlp/Fast-TransX#39]
我尝试在FB15K上运行transR，但得到的结果与项目页面上的数字相去甚远，请问会是什么原因呢？
参数设置部分，我把向量长度也设为50，迭代次数100，是不过把线程数增加到48。

**Comment by THUCSTHanxu13** [comment]
原论文里说了一点，就是TransR需要在TransE预先训练的好的向量基础上再进行训练，这个你可以先用TransE训练完之后，再导入到transR里面就可以了

**Comment by chivychao** [comment]
非常感谢你的解答，怪自己没看仔细文章
另外想请问，页面的结果是否是考虑了type constrain结果？@THUCSTHanxu13
