### ISSUE TITLE
How to create files:“set_num_l.txt” and "set_num_r" used in TranSparse

### ISSUE THREAD

**Issue by flyingfurther** [thunlp/Fast-TransX#4]
Could you please tell me how to create files:“set_num_l.txt” and "set_num_r" used in TranSparse?
I just use the file created by code that is  provided by the paper.
But I find them diffferent from your files in your code.
And I don't understand the meaning of "numLef", "numRig" and "last".
If is it convenient to share you code to create these two files?
Thank you very much.

**Comment by THUCSTHanxu13** [comment]
The origin code and dataset can be found from "http://www.nlpr.ia.ac.cn/cip/~liukang/publications.html".
