### ISSUE TITLE
TransE中O3优化导致train函数无法终止

### ISSUE THREAD

**Issue by zodiacg** [thunlp/Fast-TransX#43]
系统为Archlinux，gcc版本8.2.1

具体表现为epoch < trainTimes始终为true，导致epoch超出给定的迭代数目后仍然在进行循环

无优化时程序运行正常，-O1起即出现循环无法终止的情况。将循环中的具体迭代代码注释掉仅保留printf也可复现

**Comment by THUCSTHanxu13** [comment]
因为我用了 thread.h c的多线程库和操作系统有关，我是ubuntu上测试的，感觉我已经碰到几个非ubuntu的liunx系统上出现这个问题了，所以我也不知道是不是多线程开了优化开关之后出现了偏差

**Comment by THUCSTHanxu13** [comment]
大家好像都是无优化没问题，有优化就不能停下来了，实在不行你可以在程序里加epoch大于某个数强行halt试试。ubuntu上坑定是没问题的
