### ISSUE TITLE
请教，TransE程序有些地方看不懂

### ISSUE THREAD

**Issue by ngl567** [thunlp/Fast-TransX#44]
由于自己水平有限，对于transE中有一些地方实在看不懂，希望不吝赐教：
1. transE.cpp 负样本生成里面corrupt_head, corrupt_tail 里面大概怎么实现的负样本生成？
2. test_transE.cpp 中triple结构体里的label（包括test2id.txt文件里也有）表示什么？
希望得到解答，谢谢！

**Comment by THUCSTHanxu13** [comment]
关于负采样，你可以看一下emnlp2018年的我们的论文。另外的话，test2id里面的label就是把原来图谱里面的实体和关系的编号变成了连续数字，比如/m/asds变成1这样。
