### ISSUE TITLE
在WN18上跑TransE，结果与paper差距很大 (已解决)

### ISSUE THREAD

**Issue by ILoveSunnyleaves** [thunlp/Fast-TransX#49]
您好，我用的参数

INT threads = 8;
INT bernFlag = 0;
INT loadBinaryFlag = 0;
INT outBinaryFlag = 0;
INT trainTimes = 1000;
INT nbatches = 1;
INT dimension = 50;
REAL alpha = 0.001;
REAL margin = 1.0;

在wn18上跑TransE，结果却非常差，请问可能是哪里错了呢：

left 1226.356201 0.221600
left(filter) 1216.166016 0.232600
right 1402.401367 0.204600
right(filter) 1392.722656 0.235600
left 369.013214 0.400800
left(filter) 358.822998 0.419600
right 281.390411 0.339200
right(filter) 271.711609 0.377600
left 1095.500000 0.523810
left(filter) 1095.309570 0.523810
right 825.595215 0.547619
right(filter) 825.428589 0.547619
left 1188.984863 0.190579
left(filter) 1188.887939 0.191121
right 1205.759033 0.145642
right(filter) 1180.281006 0.209529
left 1651.449219 0.066633
left(filter) 1626.444214 0.078243
right 2118.939941 0.060071
right(filter) 2118.886475 0.060071
left 547.074341 0.532743
left(filter) 545.986755 0.560177
right 489.092926 0.541593
right(filter) 488.010620 0.574336

谢谢指教！

**Comment by THUCSTHanxu13** [comment]
给的默认参数是给fb15k的，wn18的话，你的alpha要调大，你试试0.01，然后维度调小50或者25，margin调大，4.0或者2.0。你再跑跑看

**Comment by HZhang90** [comment]
您好，谢谢您及时的回复。

我尝试了alpha=0.01，size=50，margin=2.0, 3.0, 4.0

具体的运行命令如下（目录结构与repository相同）：
训练：`./TransE -size 50 -input data/WN18/ -output results/ -alpha 0.01 -margin 4.0`
测试：`/test_TransE -size 50 -input data/WN18/ -init results/`

但是结果没有很大变化，最好的一组如下：

left 543.232788 0.211800
left(filter) 532.249207 0.230600
right 536.312012 0.197600
right(filter) 526.900208 0.221400
left 162.231995 0.418800
left(filter) 151.248398 0.458400
right 157.504593 0.401400
right(filter) 148.092804 0.442600
left 436.166656 0.357143
left(filter) 436.000000 0.357143
right 365.738098 0.380952
right(filter) 365.500000 0.380952
left 650.730347 0.197076
left(filter) 650.635071 0.198701
right 578.617188 0.153763
right(filter) 553.850586 0.202491
left 568.581543 0.147905
left(filter) 541.560852 0.184250
right 622.172668 0.146391
right(filter) 622.118103 0.146896
left 327.067261 0.342478
left(filter) 325.999115 0.359292
right 322.981415 0.352212
right(filter) 321.922119 0.376991

如果alpha调大之后，例如0.1就会不收敛。再次感谢您的帮忙。

**Comment by THUCSTHanxu13** [comment]
你用这个试试https://github.com/thunlp/OpenKE

**Comment by ILoveSunnyleaves** [comment]
好的。谢谢您！

**Comment by ILoveSunnyleaves** [comment]
另外我成功在fast-transx调整好了。再次谢谢您的帮忙。

**Comment by THUCSTHanxu13** [comment]
你把参数po出来吧，感觉对大家会有帮助的

**Comment by THUCSTHanxu13** [comment]
感谢~

**Comment by ILoveSunnyleaves** [comment]
好的，在我这里用

`./TransE -size 100 -input data/WN18/ -output results/ -alpha 0.01 -margin 2.0 `

就可以大幅度提升效果。再次感谢您的帮助。

**Comment by head-bigandhard** [comment]
您好，我用fast-transE跑出来结果和页面上也差不少，MR（Raw)平均到280了
