### ISSUE TITLE
TransH.cpp的gradient函数

### ISSUE THREAD

**Issue by hatleon** [thunlp/Fast-TransX#51]
![h](https://user-images.githubusercontent.com/25217721/55810750-9fd00c00-5b1a-11e9-85b9-f9411609ccbb.PNG)
TransH.cpp 第356行 entityVecDao（等价于头实体）只进行了一次计算，根据变量多次出现的求导法则，不是应该计算两次吗？你看ADao在gradient函数中算了四次。

**Comment by 27232xsl** [comment]
请问你搞懂了吗？我也不明白这块

**Comment by hatleon** [comment]
不好意思，我后来没理了。可能是作者觉得在计算过程中可以抵消不算，你可以按照数学求导的定义写程序跑一次看准确率。

（借鉴）机器学习中的矩阵/向量求导 - Towser的文章 - 知乎
https://zhuanlan.zhihu.com/p/25063314

**Comment by 27232xsl** [comment]
好的，谢谢你
