### ISSUE TITLE
Results of test_transE

### ISSUE THREAD

**Issue by Kyeongpil** [thunlp/Fast-TransX#53]
Hi I tried to run your codes, and when I run test_transE, I got following results:

left 12155.270508 0.143083
left(filter) 11667.890625 0.186583
right 12955.742188 0.281667
right(filter) 12945.541016 0.325417
left 1880.772949 0.156500
left(filter) 1393.394775 0.204750
right 936.673889 0.299750
right(filter) 926.475159 0.343583
left 18177.582031 0.558659
left(filter) 18177.003906 0.573184
right 30702.458984 0.537430
right(filter) 30702.173828 0.546369
left 19323.531250 0.456829
left(filter) 19322.150391 0.483516
right 38445.351562 0.353218
right(filter) 38435.953125 0.395604
left 33830.359375 0.061051
left(filter) 33046.398438 0.111928
right 13426.873047 0.515545
right(filter) 13426.180664 0.521198
left 6602.977051 0.094034
left(filter) 6090.237305 0.140246
right 9167.539062 0.202552
right(filter) 9154.329102 0.257731

I think these results are printed in
https://github.com/thunlp/Fast-TransX/blob/master/transE/test_transE.cpp#L332

However, I don't understand each for loop means because there is no explanation about these codes and results.

Could you describe the meaning of these results?
In addition, I want to know to get the results (MeanRank, HITS@10) as written in Markdown
https://github.com/thunlp/Fast-TransX#evaluation-results

Thank you.

**Comment by failable** [comment]
Still not understand those outputs.

**Comment by THUCSTHanxu13** [comment]
overall results (without type constraining)

left 12155.270508 0.143083
left(filter) 11667.890625 0.186583
right 12955.742188 0.281667
right(filter) 12945.541016 0.325417

overall results (with type constraining)

left 1880.772949 0.156500
left(filter) 1393.394775 0.204750
right 936.673889 0.299750
right(filter) 926.475159 0.343583

1-1

left 18177.582031 0.558659
left(filter) 18177.003906 0.573184
right 30702.458984 0.537430
right(filter) 30702.173828 0.546369

1-N

left 19323.531250 0.456829
left(filter) 19322.150391 0.483516
right 38445.351562 0.353218
right(filter) 38435.953125 0.395604

N-1

left 33830.359375 0.061051
left(filter) 33046.398438 0.111928
right 13426.873047 0.515545
right(filter) 13426.180664 0.521198

N-N

left 6602.977051 0.094034
left(filter) 6090.237305 0.140246
right 9167.539062 0.202552
right(filter) 9154.329102 0.257731
