### ISSUE TITLE
TransH.cpp中gradient函数中sum_x的作用是什么？

### ISSUE THREAD

**Issue by 27232xsl** [thunlp/Fast-TransX#54]
这整个函数我好像都没明白，和自己推出来的结果不一样，这个sum_x尤其看不明白

**Comment by THUCSTHanxu13** [comment]
每个向量和法向量点乘得到系数，向量-系数×法向量得到变换后的向量，然后对法向量求导的话，法向量的每一维都和法向量的其他所有维度有关系，这里提前算一下方便处理
