### ISSUE TITLE
e1_e2.txt

### ISSUE THREAD

**Issue by AndRossi** [thunlp/Fast-TransX#57]
I am trying to train PTransE on other datasets in addition to FB15K, and therefore I need to generate the corresponding e1_e2.txt file.
However I am really confused about how exactly the is e1_e2.txt is generated.

Can you please explain this to me (or, even better, share the code for generating that file, so I can study it myself)?
Thanks!

**Comment by THUCSTHanxu13** [comment]
For this, we refer to the original code of PtransE  https://github.com/thunlp/KB2E/tree/master/PTransE
