### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by logen1004** [thunlp/Fast-TransX#6]
When run the TransE and call the transetrainMode, Floating point exception occurs

**Comment by kimiqq** [comment]
@logen1004 how to solve this problem?

**Comment by THUCSTHanxu13** [comment]
My email is cst_hanxu13@163.com. You can give me more details by sending emails.

**Comment by Kevin9780** [comment]
> My email is [cst_hanxu13@163.com](mailto:cst_hanxu13@163.com). You can give me more details by sending emails.

您好，我现在遇到了相同的问题，请问您还记得当时是怎么解决的吗？谢谢！
我用了自己的数据集，数据量极大，可能是内存溢出了。但我把transD.cpp里面的所有int都换成了long long，还是报一样的错误……

**Comment by Kevin9780** [comment]
Hello, I have encountered the same problem now. Do you still remember how it was solved? 
I used my own data set. The amount of data is huge. It may be a memory overflow. I replaced all 'int' in transd.cpp with 'long long', but it still reported the same error...
