### ISSUE TITLE
How many epoches are there supposed to be? Why I've got 1500 epoches and since 10 epoch the loss has been 0 and it doesn't stop?

### ISSUE THREAD

**Issue by namespace-Pt** [thunlp/Fast-TransX#60]
调用的时候从第10轮开始就是0了但是一直不会停止训练

**Comment by Jie190916** [comment]
遇到了一样的问题，请问解决了吗

**Comment by namespace-Pt** [comment]
取消优化-O3命令，用g++ transX.cpp -o transX -pthread -march=native 训练

发送自 Windows 10 版邮件应用

发件人: Jie190916
发送时间: 2020年8月22日 17:31
收件人: thunlp/Fast-TransX
抄送: zpt; Author
主题: Re: [thunlp/Fast-TransX] How many epoches are there supposed to be?Why I've got 1500 epoches and since 10 epoch the loss has been 0 and itdoesn't stop? (#60)

遇到了一样的问题，请问解决了吗
