### ISSUE TITLE
TransE结果的问题

### ISSUE THREAD

**Issue by head-bigandhard** [thunlp/Fast-TransX#61]
您好，使用源码中给的参数，无法跑出页面上的结果，MR（Raw）取平均后到280了，比205多太多了

**Comment by THUCSTHanxu13** [comment]
MR比较容易受到部分预测结果的影响，一般参照价值不太大，一般看hits@10较多。另外可以调一下负采样模式，对MR会有影响，有时候MR低了，hits@10会跟着变低
